# Docker Compose для ISKALA + Open WebUI

services:
  # ISKALA Core сервис
  iskala-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iskala-core
    ports:
      - "8001:8001"
      - "8081:8081"
      - "8082:8082"
      - "8002:8002"
    volumes:
      - ./data:/app/data
      - ./state:/app/state
      - ./logs:/app/logs
      - ./trees:/app/trees
      - ./vault:/app/vault
      - ./rag_system:/app/rag_system
      - ./translation:/app/translation
      - ./shield:/app/shield
      - ./system_prompts:/app/system_prompts
      - ./tool_api:/app/tool_api
      - ./universal_api_connector:/app/universal_api_connector
    env_file:
      - .env
    environment:
      - ISKALA_ENV=production
      - ISKALA_PORT=8001
      - VAULT_PORT=8081
      - TRANSLATION_PORT=8082
      - RAG_PORT=8002
      - SHIELD_ENABLED=true
      - PYTHONPATH=/app
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
    restart: unless-stopped
    networks:
      - iskala-network

  # ISKALA OpenAPI Tool Server
  iskala-openapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iskala-openapi
    ports:
      - "8003:8003"
    volumes:
      - ./iskala_openapi_server.py:/app/iskala_openapi_server.py
      - ./data:/app/data
      - ./state:/app/state
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - ISKALA_BASE_URL=http://iskala-core:8001
      - VAULT_BASE_URL=http://iskala-core:8081
      - TRANSLATION_BASE_URL=http://iskala-core:8082
      - RAG_BASE_URL=http://iskala-core:8002
    restart: unless-stopped
    networks:
      - iskala-network
    depends_on:
      - iskala-core
    command: python iskala_openapi_server.py

  # Open WebUI с OpenRouter API и ISKALA Tools
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.18
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3001:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      # OpenRouter API настройки
      - OPENAI_API_BASE_URL=https://openrouter.ai/api/v1
      - OPENAI_API_KEY=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
      
      # Настройки безопасности
      - WEBUI_SECRET_KEY=iskala-secret-key-2024
      - DEFAULT_USER_ROLE=admin
      - ENABLE_SIGNUP=true
      - ENABLE_LOGIN_FORM=true
      
      # Настройки веб-сервера
      - WEBUI_HOST=0.0.0.0
      - WEBUI_PORT=8080
      - DISABLE_UI=false
      - DISABLE_API=false
      - DISABLE_AUTH=false
      
      # Дополнительные настройки
      - ENABLE_SIGNUP=true
      - ENABLE_LOGIN_FORM=true
      - ENABLE_OAUTH=false
      - ENABLE_OAUTH_GOOGLE=false
      - ENABLE_OAUTH_GITHUB=false
      - ENABLE_OAUTH_DISCORD=false
      - ENABLE_OAUTH_MICROSOFT=false
      
      # Настройки моделей (только OpenRouter API, полностью отключаем Ollama)
      - DEFAULT_MODELS=
      - DEFAULT_MODELS_OPENAI=
      - DEFAULT_MODELS_ANTHROPIC=
      - DEFAULT_MODELS_OLLAMA=
      - AUTOMATIC_MODEL_INITIALIZATION=false
      
      # Полное отключение Ollama (чтобы избежать ошибок подключения)
      - OLLAMA_BASE_URL=
      - OLLAMA_API_BASE_URL=
      - RAG_OLLAMA_BASE_URL=
      - ENABLE_OLLAMA=false
      - OLLAMA_AUTO_PULL=false
      - OLLAMA_AUTO_PULL_DISABLED=true
      - ENABLE_OLLAMA_API=false
      - OLLAMA_CONNECTION_CHECK=false
      - WHISPER_MODEL=base
      - WHISPER_MODEL_URL=
      
      # Принудительное отключение проверок Ollama
      - ENABLE_MODEL_FILTER=false
      - AUTO_UPDATE_DISABLED=true
      - BACKEND_DISABLED=false
      
      # Настройки ISKALA интеграции
      - CUSTOM_MODELS_ENABLED=true
      - CUSTOM_MODELS_BASE_URL=http://iskala-core:8001
      
      # Настройки ISKALA OpenAPI Tools
      - ENABLE_TOOLS=true
      - TOOLS_ENABLED=true
      
      # Разрешения для Workspace (включая загрузку промптов)
      - USER_PERMISSIONS_WORKSPACE_PROMPTS_ACCESS=true
      - USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS=true
      - USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ACCESS=true
      - USER_PERMISSIONS_WORKSPACE_TOOLS_ACCESS=true
      
      # Разрешения для публичного шаринга промптов
      - USER_PERMISSIONS_WORKSPACE_PROMPTS_ALLOW_PUBLIC_SHARING=true
      
      # Настройки отладки и логирования
      - LOG_LEVEL=INFO
      - ENABLE_DEBUG=true
      - ENABLE_LOGGING=true
      
      # Отключение кэширования для решения проблем с JS файлами
      - DISABLE_CACHE=true
      - CACHE_CONTROL=no-cache
      - ETAG_DISABLED=true
      
      # Настройки загрузки файлов
      - MAX_FILE_SIZE=50
      - ALLOWED_FILE_TYPES=["json","txt","md","yaml","yml"]
      
      # Настройки промптов
      - ENABLE_PROMPTS=true
      - PROMPTS_FILE_SIZE_LIMIT=100
      - PROMPTS_ALLOWED_EXTENSIONS=["json","txt","md"]
      - PROMPTS_PUBLIC_ACCESS=true
      - PROMPTS_ENABLED=true
      - PROMPTS_IMPORT_ENABLED=true
      
      # Настройки RAG (загрузка знаний)
      - ENABLE_RAG=true
      - RAG_EMBEDDING_ENGINE=openai
      - RAG_EMBEDDING_MODEL=text-embedding-3-small
      - RAG_TOP_K=3
      - RAG_RELEVANCE_THRESHOLD=0.7
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=100
      - RAG_FILE_MAX_SIZE=50
      - RAG_FILE_MAX_COUNT=10
      - RAG_ALLOWED_FILE_EXTENSIONS=["pdf","docx","txt","md","json","csv"]
      
      # Настройки загрузки файлов
      - USER_PERMISSIONS_CHAT_FILE_UPLOAD=true
      - ENABLE_RAG_LOCAL_WEB_FETCH=true
      
      # Настройки инструментов и API
      - ENABLE_DIRECT_CONNECTIONS=true
      - USER_PERMISSIONS_FEATURES_DIRECT_TOOL_SERVERS=true
      - USER_PERMISSIONS_FEATURES_CODE_INTERPRETER=true
      - USER_PERMISSIONS_FEATURES_WEB_SEARCH=true
      - USER_PERMISSIONS_FEATURES_IMAGE_GENERATION=true
      
      # Настройки веб-поиска
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=5
      
      # Настройки ISKALA OpenAPI Tools
      - CUSTOM_TOOLS_ENABLED=true
      - CUSTOM_TOOLS_BASE_URL=http://iskala-openapi:8003
    networks:
      - iskala-network
    depends_on:
      - iskala-core
      - iskala-openapi

volumes:
  open-webui-data:

networks:
  iskala-network:
    driver: bridge 