# =====================================================
# Prometheus Configuration for ISKALA Production
# =====================================================
# Comprehensive monitoring of all ISKALA services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'iskala-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alerting rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # ISKALA Graph Search Service
  - job_name: 'iskala-graph-search'
    static_configs:
      - targets: ['graph_search:8004']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # ISKALA Tool Server
  - job_name: 'iskala-tool-server'
    static_configs:
      - targets: ['tool_server:8003']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Neo4j Database
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: /db/neo4j/tx/commit
    scrape_interval: 30s
    scrape_timeout: 15s
    basic_auth:
      username: 'neo4j'
      password: '${NEO4J_PASSWORD}'

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter - Host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # Blackbox Exporter - Endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://graph_search:8004/health
        - http://tool_server:8003/health
        - http://neo4j:7474
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]  
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # Docker daemon metrics (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    metrics_path: /metrics
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'iskala-custom-metrics'
    file_sd_configs:
      - files:
        - '/etc/prometheus/custom_targets.json'
        refresh_interval: 10s

# Remote write configuration (for long-term storage)
# Uncomment and configure for production use
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true 